/**
 * VoteWise India — Quiz Page
 * AI-generated + static election knowledge quiz
 */

import { useState, useEffect, useCallback } from 'react';
import { useAppContext } from '../context/AppContext';
import { BASE_QUIZ_QUESTIONS } from '../data/electionData';
import { generateQuizQuestions } from '../services/geminiService';
import './Quiz.css';

export default function Quiz() {
  const { t, language } = useAppContext();
  const [questions, setQuestions] = useState([]);
  const [currentQ, setCurrentQ] = useState(0);
  const [selectedAnswer, setSelectedAnswer] = useState(null);
  const [showResult, setShowResult] = useState(false);
  const [score, setScore] = useState(0);
  const [answers, setAnswers] = useState([]);
  const [quizStarted, setQuizStarted] = useState(false);
  const [loading, setLoading] = useState(false);
  const [quizTopic, setQuizTopic] = useState('general');

  const topics = [
    { id: 'general', label: t('General Elections', 'सामान्य चुनाव'), icon: '🗳️' },
    { id: 'evm', label: t('EVM & VVPAT', 'EVM और VVPAT'), icon: '💻' },
    { id: 'rights', label: t('Voter Rights', 'मतदाता अधिकार'), icon: '⚖️' },
    { id: 'process', label: t('Election Process', 'चुनाव प्रक्रिया'), icon: '📋' },
  ];

  const startQuiz = useCallback(async (topic) => {
    setQuizTopic(topic);
    setLoading(true);
    setQuizStarted(true);
    setCurrentQ(0);
    setSelectedAnswer(null);
    setShowResult(false);
    setScore(0);
    setAnswers([]);

    // Try AI-generated questions first
    const aiQuestions = await generateQuizQuestions(topic, 5);
    
    if (aiQuestions && aiQuestions.length > 0) {
      setQuestions(aiQuestions);
    } else {
      // Fallback to static questions (shuffle and pick 5)
      const shuffled = [...BASE_QUIZ_QUESTIONS].sort(() => Math.random() - 0.5);
      setQuestions(shuffled.slice(0, Math.min(5, shuffled.length)));
    }

    setLoading(false);
  }, []);

  const handleAnswer = (index) => {
    if (selectedAnswer !== null) return;
    
    setSelectedAnswer(index);
    const isCorrect = index === questions[currentQ].correct;
    if (isCorrect) setScore(prev => prev + 1);
    setAnswers(prev => [...prev, { questionIndex: currentQ, selected: index, correct: isCorrect }]);
  };

  const nextQuestion = () => {
    if (currentQ < questions.length - 1) {
      setCurrentQ(prev => prev + 1);
      setSelectedAnswer(null);
    } else {
      setShowResult(true);
    }
  };

  const getScoreEmoji = () => {
    const percentage = (score / questions.length) * 100;
    if (percentage >= 80) return '🏆';
    if (percentage >= 60) return '⭐';
    if (percentage >= 40) return '📚';
    return '💪';
  };

  const getScoreMessage = () => {
    const percentage = (score / questions.length) * 100;
    if (percentage >= 80) return t('Excellent! You\'re an election expert!', 'उत्कृष्ट! आप चुनाव विशेषज्ञ हैं!');
    if (percentage >= 60) return t('Good job! You know your elections well.', 'अच्छा! आप चुनावों को अच्छी तरह जानते हैं।');
    if (percentage >= 40) return t('Not bad! Keep learning to improve.', 'बुरा नहीं! सीखते रहें।');
    return t('Keep learning! Explore our Learn section for more.', 'सीखते रहें! और जानने के लिए Learn सेक्शन देखें।');
  };

  if (!quizStarted) {
    return (
      <main className="quiz-page" id="main-content">
        <div className="container">
          <div className="section-header">
            <h1 className="section-title">
              {t('Election', 'चुनाव')}{' '}
              <span className="gradient-text">{t('Knowledge Quiz', 'ज्ञान क्विज़')}</span>
            </h1>
            <p className="section-subtitle">
              {t(
                'Test your knowledge about Indian elections with AI-generated questions!',
                'AI-जनित प्रश्नों के साथ भारतीय चुनावों के बारे में अपना ज्ञान परखें!'
              )}
            </p>
          </div>

          <div className="quiz-topics">
            <h2 className="quiz-topics__heading">
              {t('Choose a Topic', 'एक विषय चुनें')}
            </h2>
            <div className="quiz-topics__grid">
              {topics.map((topic) => (
                <button
                  key={topic.id}
                  className="quiz-topic-card glass-card"
                  onClick={() => startQuiz(topic.id)}
                  id={`quiz-topic-${topic.id}`}
                >
                  <span className="quiz-topic-card__icon" aria-hidden="true">{topic.icon}</span>
                  <span className="quiz-topic-card__label">{topic.label}</span>
                  <span className="quiz-topic-card__start">{t('Start Quiz →', 'क्विज़ शुरू करें →')}</span>
                </button>
              ))}
            </div>
            <p className="quiz-topics__ai-note">
              ✨ {t('Questions are generated by Gemini AI for a unique experience every time!', 'हर बार एक अनूठा अनुभव के लिए प्रश्न Gemini AI द्वारा उत्पन्न किए जाते हैं!')}
            </p>
          </div>
        </div>
      </main>
    );
  }

  if (loading) {
    return (
      <main className="quiz-page" id="main-content">
        <div className="container">
          <div className="quiz-loading">
            <div className="loader"></div>
            <p>{t('AI is generating your quiz questions...', 'AI आपके क्विज़ प्रश्न तैयार कर रहा है...')}</p>
          </div>
        </div>
      </main>
    );
  }

  if (showResult) {
    return (
      <main className="quiz-page" id="main-content">
        <div className="container">
          <div className="quiz-result animate-scale-in">
            <div className="quiz-result__card glass-card">
              <div className="quiz-result__emoji" aria-hidden="true">{getScoreEmoji()}</div>
              <h2 className="quiz-result__title">{t('Quiz Complete!', 'क्विज़ पूरा!')}</h2>
              
              <div className="quiz-result__score">
                <span className="quiz-result__score-num">{score}</span>
                <span className="quiz-result__score-total">/ {questions.length}</span>
              </div>

              <p className="quiz-result__message">{getScoreMessage()}</p>

              {/* Answer Review */}
              <div className="quiz-result__review">
                {questions.map((q, i) => (
                  <div key={i} className={`quiz-review-item ${answers[i]?.correct ? 'quiz-review-item--correct' : 'quiz-review-item--wrong'}`}>
                    <div className="quiz-review-item__q">
                      <span>{answers[i]?.correct ? '✅' : '❌'}</span>
                      <span>{language === 'hi' && q.questionHi ? q.questionHi : q.question}</span>
                    </div>
                    {!answers[i]?.correct && (
                      <p className="quiz-review-item__explanation">
                        💡 {q.explanation}
                      </p>
                    )}
                  </div>
                ))}
              </div>

              <div className="quiz-result__actions">
                <button onClick={() => startQuiz(quizTopic)} className="btn btn--primary">
                  🔄 {t('Retake Quiz', 'फिर से क्विज़ लें')}
                </button>
                <button onClick={() => setQuizStarted(false)} className="btn btn--outline">
                  📚 {t('Choose Another Topic', 'दूसरा विषय चुनें')}
                </button>
              </div>
            </div>
          </div>
        </div>
      </main>
    );
  }

  const q = questions[currentQ];

  return (
    <main className="quiz-page" id="main-content">
      <div className="container">
        <div className="quiz-active">
          {/* Progress */}
          <div className="quiz-progress">
            <div className="quiz-progress__bar">
              <div
                className="quiz-progress__fill"
                style={{ width: `${((currentQ + 1) / questions.length) * 100}%` }}
              ></div>
            </div>
            <div className="quiz-progress__info">
              <span>{t('Question', 'प्रश्न')} {currentQ + 1}/{questions.length}</span>
              <span>{t('Score', 'स्कोर')}: {score}</span>
            </div>
          </div>

          {/* Question Card */}
          <div className="quiz-question glass-card animate-fade-in" key={currentQ}>
            <h2 className="quiz-question__text">
              {language === 'hi' && q.questionHi ? q.questionHi : q.question}
            </h2>

            <div className="quiz-options" role="radiogroup" aria-label="Answer options">
              {q.options.map((option, i) => {
                let optionClass = 'quiz-option';
                if (selectedAnswer !== null) {
                  if (i === q.correct) optionClass += ' quiz-option--correct';
                  else if (i === selectedAnswer) optionClass += ' quiz-option--wrong';
                }

                return (
                  <button
                    key={i}
                    className={optionClass}
                    onClick={() => handleAnswer(i)}
                    disabled={selectedAnswer !== null}
                    role="radio"
                    aria-checked={selectedAnswer === i}
                    id={`option-${i}`}
                  >
                    <span className="quiz-option__letter">
                      {String.fromCharCode(65 + i)}
                    </span>
                    <span className="quiz-option__text">{option}</span>
                    {selectedAnswer !== null && i === q.correct && (
                      <span className="quiz-option__icon" aria-hidden="true">✅</span>
                    )}
                    {selectedAnswer !== null && i === selectedAnswer && i !== q.correct && (
                      <span className="quiz-option__icon" aria-hidden="true">❌</span>
                    )}
                  </button>
                );
              })}
            </div>

            {/* Explanation */}
            {selectedAnswer !== null && q.explanation && (
              <div className="quiz-explanation animate-fade-in-up">
                <span aria-hidden="true">💡</span>
                <p>{q.explanation}</p>
              </div>
            )}

            {/* Next Button */}
            {selectedAnswer !== null && (
              <button className="btn btn--primary quiz-next-btn animate-fade-in" onClick={nextQuestion}>
                {currentQ < questions.length - 1
                  ? `${t('Next Question', 'अगला प्रश्न')} →`
                  : `📊 ${t('See Results', 'परिणाम देखें')}`
                }
              </button>
            )}
          </div>
        </div>
      </div>
    </main>
  );
}
